### ISSUE TITLE
Dists might not have been properly uploaded to npm

### ISSUE THREAD

**Issue by BobLiu0518** [novrain/vue3-lumino-widget#8]
## Issue Description

An error occurred when I tried to import the module `vue3-lumino-widget` using the following code provided in the `README.md`:
```typescript
import { LuminoBoxPanel, LuminoWidget } from "vue3-lumino-widget"
```
The following error was displayed:
```
Failed to resolve entry for package "vue3-lumino-widget".
The package may have incorrect main/module/exports specified in its package.json.
```

Additionally, [Publint](https://publint.dev/vue3-lumino-widget@1.0.8) reports that the files specified by "main", "module" and "exports" fields in `package.json` do not exist. However, they're correctly generated when I cloned the repo and ran `pnpm i && pnpm run build` locally.

## My guess

I suspect that these files might not have been properly uploaded to npm, as the `dist` folder is included in `.npmignore`.

I am relatively new to npm, so I apologize for any misunderstanding or errors in my analysis.

**Comment by novrain** [comment]
yes, you are right.

i will fix it, thank you.
